# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [2]:
## Enter answer here.
print("What is your age?")
Age = int(input())
if Age < 31 :
  print("You are less than a billion years old")



What is your age?
21
You are less than a billion years old


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [3]:
## Enter answer here.

name = ["Lea", "Allison", "Hayley", "Liz", "Julia", "Meredith", "Katie", "Emma", "Max", "Anna"]
for i in name:
  print("Good morning,", i)

Good morning, Lea
Good morning, Allison
Good morning, Hayley
Good morning, Liz
Good morning, Julia
Good morning, Meredith
Good morning, Katie
Good morning, Emma
Good morning, Max
Good morning, Anna


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [4]:
## Enter answer here.

list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in list:
  if i%2 == 0:
    print(i)

2
4
6
8
10
12
14


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [9]:
## Enter answer here.

nums = [0,-1.25,15.86,]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2
nums = [0,3.33,17,-36,5.5,22,58.99,43,-21,10]
method2_squares = [i**2 for i in nums]
print(method2_squares)

[0, 1.5625, 251.53959999999998]
[0, 11.0889, 289, 1296, 30.25, 484, 3479.8201000000004, 1849, 441, 100]


### Q5. Write a program to print a year if it is a leap year.

In [10]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2021
2021 is not a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [11]:
names = ["Lea", "Allison", "Meredith"]
uppercase_names = [name.upper() for name in names]
print(uppercase_names)

['LEA', 'ALLISON', 'MEREDITH']


### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [12]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np



In [18]:
# Q7a
original = np.random.uniform(10, 100, 100)
print(original)
largest = np.max(original)
smallest = np.min(original)
max_val = np.max(original)
min_val = np.min(original)
median_val = np.median(original)
std_dev = np.std(original)
print("Largest:", largest)
print("Smallest:", smallest)
print("Max:", max_val)
print("Min:", min_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)

[33.37262901 94.17447946 93.10054087 72.69017919 39.46504924 30.08998289
 39.40016041 57.54780262 98.52382346 65.41844082 23.39410197 73.55224692
 96.85849735 19.23449018 63.13511709 21.88724852 54.15833026 37.75469507
 59.94601562 71.3838603  48.05682806 72.5258211  28.70633143 51.53969802
 31.79724065 83.03533982 35.5227049  51.24074483 73.68158093 40.3331648
 25.60864957 66.56543191 84.75559436 94.82792393 15.09852499 15.27945448
 65.52101636 21.93254748 96.16513341 82.63195292 75.06088925 52.67940416
 95.50073165 83.97244367 44.67440658 94.96686703 67.01423932 42.77582499
 79.04320441 85.32156662 71.89956521 73.8933847  75.12525375 21.13599401
 48.60177959 72.01476212 35.7093262  64.96109976 13.89179107 32.93680189
 11.48824822 73.07150558 37.98951538 79.1040035  91.33895945 23.90212017
 16.74359325 10.87923118 20.15616967 95.70433103 78.27382881 32.98972003
 25.06434892 99.65412376 58.74120997 41.00334715 81.80633573 78.1789439
 85.85672375 98.90594097 44.6819987  54.60153223 13.2

In [21]:
# Q7b
orig_sqrt = np.sqrt(original)
print(orig_sqrt)

[5.77690479 9.70435363 9.64886215 8.52585358 6.2821214  5.4854337
 6.27695471 7.5860268  9.92591676 8.08816672 4.83674498 8.57626066
 9.84167147 4.38571433 7.94576095 4.67838097 7.35923435 6.14448493
 7.74248123 8.44889699 6.93230323 8.51620931 5.35782898 7.17911541
 5.63890421 9.1123729  5.96009269 7.15826409 8.58379758 6.35083969
 5.06049894 8.15876412 9.20628016 9.73796303 3.88568205 3.90889428
 8.09450532 4.68321978 9.80638228 9.09021193 8.66376877 7.25805788
 9.77244758 9.16364795 6.68389157 9.74509451 8.18622253 6.540323
 8.89062452 9.23696739 8.47936113 8.59612614 8.66748255 4.59738991
 6.97149766 8.4861512  5.97572809 8.0598449  3.72716931 5.73905932
 3.38943184 8.54818727 6.16356353 8.89404315 9.5571418  4.88897946
 4.0918936  3.29836796 4.4895623  9.78285904 8.84724979 5.74366782
 5.00643076 9.98269121 7.66428144 6.4033856  9.0446855  8.84188577
 9.26589034 9.9451466  6.68445949 7.38928496 3.63334722 9.3441407
 7.82212839 3.87388984 5.54601527 8.78250301 5.30783043 4.67179894

In [22]:
# Q8a
mat_array = original.reshape(20, 5)
print("\nmat_array:\n", mat_array)


mat_array:
 [[33.37262901 94.17447946 93.10054087 72.69017919 39.46504924]
 [30.08998289 39.40016041 57.54780262 98.52382346 65.41844082]
 [23.39410197 73.55224692 96.85849735 19.23449018 63.13511709]
 [21.88724852 54.15833026 37.75469507 59.94601562 71.3838603 ]
 [48.05682806 72.5258211  28.70633143 51.53969802 31.79724065]
 [83.03533982 35.5227049  51.24074483 73.68158093 40.3331648 ]
 [25.60864957 66.56543191 84.75559436 94.82792393 15.09852499]
 [15.27945448 65.52101636 21.93254748 96.16513341 82.63195292]
 [75.06088925 52.67940416 95.50073165 83.97244367 44.67440658]
 [94.96686703 67.01423932 42.77582499 79.04320441 85.32156662]
 [71.89956521 73.8933847  75.12525375 21.13599401 48.60177959]
 [72.01476212 35.7093262  64.96109976 13.89179107 32.93680189]
 [11.48824822 73.07150558 37.98951538 79.1040035  91.33895945]
 [23.90212017 16.74359325 10.87923118 20.15616967 95.70433103]
 [78.27382881 32.98972003 25.06434892 99.65412376 58.74120997]
 [41.00334715 81.80633573 78.1789439  85.8

In [24]:
# Q8b
column_means = np.mean(mat_array, axis=0)
print("\nColumn Means:", column_means)


Column Means: [46.65271394 54.06042695 54.01204108 62.34420529 60.90369015]


In [25]:
# Q8c
row_sums = np.sum(mat_array, axis=1)
print("\nRow Sums:", row_sums)



Row Sums: [332.80287777 290.98021021 276.17445351 245.13014977 232.62591925
 283.81353528 286.85612475 281.53010465 351.88787531 369.12170237
 290.65597726 219.51378102 292.99223212 167.3854453  294.72323149
 385.7512915  260.98340097 172.8964362  157.33569837 366.30110127]


In [26]:
# Q8d
transpose_array = mat_array.T
print("\nTranspose Array Shape:", transpose_array.shape)

transpose_column_means = np.mean(transpose_array, axis=0)
transpose_row_sums = np.sum(transpose_array, axis=1)
print("\nTranspose Column Means:", transpose_column_means)
print("\nTranspose Row Sums:", transpose_row_sums)


Transpose Array Shape: (5, 20)

Transpose Column Means: [66.56057555 58.19604204 55.2348907  49.02602995 46.52518385 56.76270706
 57.37122495 56.30602093 70.37757506 73.82434047 58.13119545 43.9027562
 58.59844642 33.47708906 58.9446463  77.1502583  52.19668019 34.57928724
 31.46713967 73.26022025]

Transpose Row Sums: [ 933.05427889 1081.20853896 1080.24082157 1246.88410589 1218.07380307]


In [27]:
# Q9a
subset_3_to_10 = mat_array[2:10, :]
print("\nSubset (Rows 3-10):\n", subset_3_to_10)


Subset (Rows 3-10):
 [[23.39410197 73.55224692 96.85849735 19.23449018 63.13511709]
 [21.88724852 54.15833026 37.75469507 59.94601562 71.3838603 ]
 [48.05682806 72.5258211  28.70633143 51.53969802 31.79724065]
 [83.03533982 35.5227049  51.24074483 73.68158093 40.3331648 ]
 [25.60864957 66.56543191 84.75559436 94.82792393 15.09852499]
 [15.27945448 65.52101636 21.93254748 96.16513341 82.63195292]
 [75.06088925 52.67940416 95.50073165 83.97244367 44.67440658]
 [94.96686703 67.01423932 42.77582499 79.04320441 85.32156662]]


In [28]:
# Q9b
subset_last_5_rows_2_cols = mat_array[-5:, -2:]
print("\nSubset (Last 5 Rows, Last 2 Columns):\n", subset_last_5_rows_2_cols)
print("Shape:", subset_last_5_rows_2_cols.shape)



Subset (Last 5 Rows, Last 2 Columns):
 [[85.85672375 98.90594097]
 [87.31296548 61.18569251]
 [28.17306383 21.82570534]
 [10.41087928 75.4780335 ]
 [71.56389872 94.09602481]]
Shape: (5, 2)


In [29]:
# Q9c
subset_first_3_rows_last_10_cols = transpose_array[:3, -10:]
print("\nSubset (First 3 Rows, Last 10 Columns of Transpose):\n", subset_first_3_rows_last_10_cols)


Subset (First 3 Rows, Last 10 Columns of Transpose):
 [[71.89956521 72.01476212 11.48824822 23.90212017 78.27382881 41.00334715
  44.6819987  15.00702246 29.79476476 94.23663069]
 [73.8933847  35.7093262  73.07150558 16.74359325 32.98972003 81.80633573
  54.60153223 30.75828539 29.65985443 30.86116664]
 [75.12525375 64.96109976 37.98951538 10.87923118 25.06434892 78.1789439
  13.20121204 77.13235917 11.99216641 75.54338041]]


### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [32]:
# Write your answer here.
import numpy as np
diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto',
        'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]
menu = []
for i in range(len(diet)):
    if diet[i] in ['vegetarian', 'vegan']:
        meal = 'veg. fried rice with whiskey' if age[i] >= 21 else 'veg. fried rice with mocktail'
    elif diet[i] == 'pescetarian':
        meal = 'fish and white wine' if age[i] >= 21 else 'fish with mocktail'
    elif diet[i] in ['keto', 'omnivore']:
        meal = 'steak and red wine' if age[i] >= 21 else 'steak with mocktail'
    menu.append(meal)
print(menu)


['veg. fried rice with whiskey', 'fish with mocktail', 'veg. fried rice with mocktail', 'steak and red wine', 'fish and white wine', 'steak with mocktail', 'steak and red wine', 'veg. fried rice with whiskey', 'steak with mocktail', 'steak and red wine', 'veg. fried rice with mocktail', 'steak with mocktail', 'steak and red wine', 'veg. fried rice with whiskey', 'veg. fried rice with whiskey']
